blank_issues_enabled: false
contact_links:
  - name: Discuss TodoMVC
    url: https://github.com/okTurtles/todomvc/discussions
    about: Use issues to report bugs or request features. Everything else goes here.
